server:
  port: 8080
  servlet:
    context-path: /journal

spring:
  application:
    name: JournalApp

  datasource:
    url: jdbc:mysql://localhost:3306/journal_crud
    username: root
    password: 
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#The first priority if there is both .properties and .yml file will be for application.properties file but we will have to delete the properties file for now



#For reference what was written in application.properties file is as below:
#spring.application.name=JournalApp

#spring.datasource.url=jdbc:mysql://localhost:3306/journal_crud
#spring.datasource.username=root
#spring.datasource.password=
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#server.port=8080
#server.servlet.context-path=/journal
#Have to write the same in application.yml file